[package]
name = "solana-program-counter-program"
version = "1.0.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
solana-program = "2.2.1"

[lib]
crate-type = [ "cdylib", "lib" ]

[dev-dependencies]
mollusk-svm = "0.1.5"
solana-sdk = "2.2.2"
